print('*  * **** *     ***   *** ')
print('*  * *    *    *   * *   *')
print('**** ***  *    *   * *   *', ' world!')
print('*  * *    *    *   * *   *')
print('*  * **** ****  ***   *** ')
#print('Hello, world!')